Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
# pystan 3 bug fixing
# RuntimeError: asyncio.run() cannot be called from a running event loop
import nest_asyncio
nest_asyncio.apply()
import stan

#----------------------------------------------
# Create the Stan model
#  this is done by defining a string of Stan code.

fit_code = """
data {
    int<lower=0> N; // number of points
    real x[N];      // x values
    real y[N];      // y values
    real sy[N];     // y uncertainties
}

parameters {
    real alpha;
    real beta;
}

transformed parameters {
    real ymodel[N];
    for (j in 1:N)
        ymodel[j] = beta + alpha * x[j];
}

model {
    alpha ~ uniform(0, 100);
    beta ~ uniform(0, 100);
    y ~ normal(ymodel, sy);
}
"""

# perform the fit
guess = {'alpha': 0.45, 'beta': 30}
fit_data = {'N': len(x), 'x': x, 'y': y, 'sy': sy}
posterior = stan.build(fit_code, data=fit_data, random_seed=1)
traces_ols = posterior.sample(num_chains=4, num_samples=25000, init=[guess] * 4)
# extract the traces
traces = [traces_ols['alpha'], traces_ols['beta']]
------------------

----- stdout -----
Building...
----- stdout -----

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[7], line 41[0m
[1;32m     39[0m guess [38;5;241m=[39m {[38;5;124m'[39m[38;5;124malpha[39m[38;5;124m'[39m: [38;5;241m0.45[39m, [38;5;124m'[39m[38;5;124mbeta[39m[38;5;124m'[39m: [38;5;241m30[39m}
[1;32m     40[0m fit_data [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mN[39m[38;5;124m'[39m: [38;5;28mlen[39m(x), [38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m: x, [38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m: y, [38;5;124m'[39m[38;5;124msy[39m[38;5;124m'[39m: sy}
[0;32m---> 41[0m posterior [38;5;241m=[39m [43mstan[49m[38;5;241;43m.[39;49m[43mbuild[49m[43m([49m[43mfit_code[49m[43m,[49m[43m [49m[43mdata[49m[38;5;241;43m=[39;49m[43mfit_data[49m[43m,[49m[43m [49m[43mrandom_seed[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m
[1;32m     42[0m traces_ols [38;5;241m=[39m posterior[38;5;241m.[39msample(num_chains[38;5;241m=[39m[38;5;241m4[39m, num_samples[38;5;241m=[39m[38;5;241m25000[39m, init[38;5;241m=[39m[guess] [38;5;241m*[39m [38;5;241m4[39m)
[1;32m     43[0m [38;5;66;03m# extract the traces[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/stan/model.py:519[0m, in [0;36mbuild[0;34m(program_code, data, random_seed)[0m
[1;32m    516[0m         [38;5;28;01mreturn[39;00m Model(model_name, program_code, data, param_names, constrained_param_names, dims, random_seed)
[1;32m    518[0m [38;5;28;01mtry[39;00m:
[0;32m--> 519[0m     [38;5;28;01mreturn[39;00m [43masyncio[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43mgo[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    520[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyboardInterrupt[39;00m:
[1;32m    521[0m     [38;5;28;01mreturn[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nest_asyncio.py:30[0m, in [0;36m_patch_asyncio.<locals>.run[0;34m(main, debug)[0m
[1;32m     28[0m task [38;5;241m=[39m asyncio[38;5;241m.[39mensure_future(main)
[1;32m     29[0m [38;5;28;01mtry[39;00m:
[0;32m---> 30[0m     [38;5;28;01mreturn[39;00m [43mloop[49m[38;5;241;43m.[39;49m[43mrun_until_complete[49m[43m([49m[43mtask[49m[43m)[49m
[1;32m     31[0m [38;5;28;01mfinally[39;00m:
[1;32m     32[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m task[38;5;241m.[39mdone():

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nest_asyncio.py:98[0m, in [0;36m_patch_loop.<locals>.run_until_complete[0;34m(self, future)[0m
[1;32m     95[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m f[38;5;241m.[39mdone():
[1;32m     96[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[1;32m     97[0m         [38;5;124m'[39m[38;5;124mEvent loop stopped before Future completed.[39m[38;5;124m'[39m)
[0;32m---> 98[0m [38;5;28;01mreturn[39;00m [43mf[49m[38;5;241;43m.[39;49m[43mresult[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/futures.py:178[0m, in [0;36mFuture.result[0;34m(self)[0m
[1;32m    176[0m [38;5;28mself[39m[38;5;241m.[39m__log_traceback [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    177[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 178[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception
[1;32m    179[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_result

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/tasks.py:280[0m, in [0;36mTask.__step[0;34m(***failed resolving arguments***)[0m
[1;32m    276[0m [38;5;28;01mtry[39;00m:
[1;32m    277[0m     [38;5;28;01mif[39;00m exc [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    278[0m         [38;5;66;03m# We use the `send` method directly, because coroutines[39;00m
[1;32m    279[0m         [38;5;66;03m# don't have `__iter__` and `__next__` methods.[39;00m
[0;32m--> 280[0m         result [38;5;241m=[39m [43mcoro[49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[38;5;28;43;01mNone[39;49;00m[43m)[49m
[1;32m    281[0m     [38;5;28;01melse[39;00m:
[1;32m    282[0m         result [38;5;241m=[39m coro[38;5;241m.[39mthrow(exc)

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/stan/model.py:498[0m, in [0;36mbuild.<locals>.go[0;34m()[0m
[1;32m    496[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(error_type)
[1;32m    497[0m     [38;5;28;01melse[39;00m:
[0;32m--> 498[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(exception_body)
[1;32m    499[0m building_output[38;5;241m.[39mclear() [38;5;28;01mif[39;00m io[38;5;241m.[39msupports_ansi() [38;5;28;01melse[39;00m building_output[38;5;241m.[39mwrite([38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[1;32m    500[0m [38;5;28;01mif[39;00m model_in_cache:

[0;31mRuntimeError[0m: Error in '/tmp/httpstan_jji5wpuj/model_rfnfx7fe.stan', line 15, column 4: Declaration
    of arrays by placing brackets after a variable name was removed in Stan
    2.33.0. Instead use the array keyword before the type. This can be
    changed automatically using the auto-format flag to stanc
Error in '/tmp/httpstan_jji5wpuj/model_rfnfx7fe.stan', line 6, column 4: Declaration
    of arrays by placing brackets after a variable name was removed in Stan
    2.33.0. Instead use the array keyword before the type. This can be
    changed automatically using the auto-format flag to stanc
Error in '/tmp/httpstan_jji5wpuj/model_rfnfx7fe.stan', line 5, column 4: Declaration
    of arrays by placing brackets after a variable name was removed in Stan
    2.33.0. Instead use the array keyword before the type. This can be
    changed automatically using the auto-format flag to stanc
Error in '/tmp/httpstan_jji5wpuj/model_rfnfx7fe.stan', line 4, column 4: Declaration
    of arrays by placing brackets after a variable name was removed in Stan
    2.33.0. Instead use the array keyword before the type. This can be
    changed automatically using the auto-format flag to stanc

